import { AppConfig } from '../types';

export function generateElectronMainCode(config: AppConfig): string {
  const hotkeysJSON = JSON.stringify(config.hotkeys, null, 2);
  const providersJSON = JSON.stringify(config.providers, null, 2);

  return `/**
 * QuickKeys AI - Windows Native Desktop App Main Process
 * Auto-generated by QuickKeys AI Studio
 */

const { app, BrowserWindow, globalShortcut, ipcMain, Tray, Menu, clipboard, screen } = require('electron');
const path = require('path');
const http = require('http');
const https = require('https');

let mainWindow = null;
let overlayWindow = null;
let tray = null;

// User Config
const APP_CONFIG = {
  providers: ${providersJSON},
  hotkeys: ${hotkeysJSON}
};

function createOverlayWindow() {
  const primaryDisplay = screen.getPrimaryDisplay();
  const { width, height } = primaryDisplay.workAreaSize;

  overlayWindow = new BrowserWindow({
    width: 580,
    height: 420,
    show: false,
    frame: false,
    alwaysOnTop: true,
    transparent: true,
    resizable: true,
    skipTaskbar: true,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
    },
  });

  overlayWindow.loadFile(path.join(__dirname, 'overlay.html'));

  overlayWindow.on('blur', () => {
    // Optionally hide when clicking outside if enabled
  });
}

function createMainWindow() {
  mainWindow = new BrowserWindow({
    width: 1100,
    height: 750,
    title: 'QuickKeys AI - Windows Settings & Hotkey Studio',
    icon: path.join(__dirname, 'icon.ico'),
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
    },
  });

  mainWindow.loadFile(path.join(__dirname, 'index.html'));
}

function registerGlobalHotkeys() {
  globalShortcut.unregisterAll();

  // Register AI Anywhere Launcher shortcut (Alt + Space)
  try {
    globalShortcut.register('Alt+Space', () => {
      if (overlayWindow) {
        overlayWindow.webContents.send('open-ai-anywhere');
        overlayWindow.show();
        overlayWindow.focus();
      }
    });
  } catch (err) {
    console.error('Error registering AI Anywhere hotkey (Alt+Space):', err);
  }

  // Register Quick Notes shortcut (Alt + N)
  try {
    globalShortcut.register('Alt+N', () => {
      if (overlayWindow) {
        overlayWindow.webContents.send('open-quick-notes');
        overlayWindow.show();
        overlayWindow.focus();
      }
    });
  } catch (err) {
    console.error('Error registering Quick Notes hotkey (Alt+N):', err);
  }

  APP_CONFIG.hotkeys.forEach((preset) => {
    if (!preset.isEnabled) return;

    // Format hotkey combo string for Electron (e.g. "Ctrl+Alt+P")
    let accelerator = preset.comboString
      .replace(/\\+/g, '+')
      .replace(/\\s+/g, '')
      .replace(/Win/g, 'Super');

    try {
      const registered = globalShortcut.register(accelerator, () => {
        handleHotkeyTrigger(preset);
      });

      if (!registered) {
        console.warn('Failed to register shortcut:', accelerator);
      } else {
        console.log('Successfully registered shortcut:', accelerator);
      }
    } catch (err) {
      console.error('Error registering hotkey:', accelerator, err);
    }
  });
}

async function handleHotkeyTrigger(preset) {
  // 1. Simulate Ctrl+C to copy selected text from any Windows app
  const activeText = await captureSelectedTextFromWindows();

  // 2. Get cursor position to place floating overlay near text
  const cursorPoint = screen.getCursorScreenPoint();
  const primaryDisplay = screen.getPrimaryDisplay();
  const bounds = primaryDisplay.bounds;

  let posX = Math.min(cursorPoint.x + 15, bounds.width - 600);
  let posY = Math.min(cursorPoint.y + 15, bounds.height - 450);

  if (posX < 0) posX = 20;
  if (posY < 0) posY = 20;

  if (overlayWindow) {
    overlayWindow.setPosition(posX, posY);
    overlayWindow.show();
    overlayWindow.focus();

    // Send payload to overlay window renderer
    overlayWindow.webContents.send('trigger-ai-hotkey', {
      preset,
      inputText: activeText || 'No text selected. Type or paste prompt here...',
    });
  }
}

function captureSelectedTextFromWindows() {
  return new Promise((resolve) => {
    const previousClip = clipboard.readText();
    clipboard.writeText(''); // Clear clipboard

    // Using RobotJS or PowerShell keybd_event simulation in production
    // Simple fallback: read current clipboard after delay
    setTimeout(() => {
      const selected = clipboard.readText();
      if (!selected || selected.trim() === '') {
        resolve(previousClip); // Fallback to existing clipboard
      } else {
        resolve(selected);
      }
    }, 150);
  });
}

function setupTrayIcon() {
  const contextMenu = Menu.buildFromTemplate([
    { label: 'QuickKeys AI - Active', enabled: false },
    { type: 'separator' },
    { label: 'Open Settings Studio', click: () => { mainWindow?.show(); } },
    { label: 'Reload Hotkeys', click: () => { registerGlobalHotkeys(); } },
    { type: 'separator' },
    { label: 'Exit QuickKeys AI', click: () => { app.quit(); } },
  ]);

  // tray = new Tray(path.join(__dirname, 'icon.ico'));
  // tray.setToolTip('QuickKeys AI Windows Assistant');
  // tray.setContextMenu(contextMenu);
}

app.whenReady().then(() => {
  createOverlayWindow();
  createMainWindow();
  registerGlobalHotkeys();
  // setupTrayIcon();

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createMainWindow();
  });
});

app.on('will-quit', () => {
  globalShortcut.unregisterAll();
});
`;
}

export function generateWindowsInstallerScript(): string {
  return `# QuickKeys AI - Automated Windows PowerShell Setup Script
# Run this script in PowerShell as Administrator to install QuickKeys AI locally on Windows

Write-Host "==================================================" -ForegroundColor Cyan
Write-Host " QuickKeys AI - Windows Native Application Installer" -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan

# Check Node.js installation
$nodeVersion = node -v 2>$null
if (-not $nodeVersion) {
    Write-Host "[!] Node.js is required to build QuickKeys AI." -ForegroundColor Red
    Write-Host "Downloading and installing Node.js LTS..." -ForegroundColor Yellow
    winget install OpenJS.NodeJS.LTS --silent --accept-package-agreements --accept-source-agreements
} else {
    Write-Host "[+] Node.js detected: $nodeVersion" -ForegroundColor Green
}

# Directory Setup
$installDir = "$env:LOCALAPPDATA\\QuickKeysAI"
Write-Host "[*] Setting up install directory: $installDir" -ForegroundColor Yellow

if (-not (Test-Path $installDir)) {
    New-Item -ItemType Directory -Force -Path $installDir | Out-Null
}

Set-Location $installDir

Write-Host "[*] Extracting QuickKeys AI package components..." -ForegroundColor Yellow
npm init -y
npm install electron electron-builder @google/genai --save

Write-Host "[*] Building Windows Executable Installer (.exe)..." -ForegroundColor Yellow
npx electron-builder --win nsis --x64

Write-Host "==================================================" -ForegroundColor Green
Write-Host "[SUCCESS] QuickKeys AI Windows Installer Created!" -ForegroundColor Green
Write-Host "Setup File: $installDir\\dist\\QuickKeys-AI-Setup.exe" -ForegroundColor Green
Write-Host "You can now run QuickKeys-AI-Setup.exe to install on any Windows machine!" -ForegroundColor White
Write-Host "==================================================" -ForegroundColor Green
`;
}

export function generateDesktopReadme(config: AppConfig): string {
  return `# QuickKeys AI - Windows Native Application & Setup Guide

QuickKeys AI turns any key combination (\`Ctrl + Alt + P\`, \`Alt + Space\`, etc.) into an instant AI floating overlay on Windows.

---

## 🚀 Quick Setup Instructions for Windows

### Method 1: Automated Installer (Recommended)
1. Download or export the project files to a folder on your Windows PC (e.g., \`C:\\QuickKeysAI\`).
2. Open **PowerShell** in that folder and run:
   \`\`\`powershell
   .\\install.ps1
   \`\`\`
3. Run the generated installer setup file in \`dist/QuickKeys-AI-Setup.exe\`.

---

### Method 2: Local Development Setup

#### Prerequisites:
- **Windows 10 / 11** (64-bit)
- **Node.js** v18 or higher (Download from [nodejs.org](https://nodejs.org/))

#### Commands:
\`\`\`bash
# 1. Clone or extract project repository
cd QuickKeysAI

# 2. Install dependencies
npm install

# 3. Start QuickKeys AI in local development mode
npm run dev

# 4. Build Standalone Portable Executable (.exe) for Windows
npm run build:exe
\`\`\`

---

## ⌨️ Configured Hotkey Presets

- **Alt + N**: **Quick Notes Overlay** (*Global popup for notes capture, search, pinning & AI refinement*)
${config.hotkeys
  .map(
    (hk) =>
      `- **${hk.comboString}**: ${hk.title} (*Provider:* ${hk.provider.toUpperCase()} | *Model:* ${hk.model})`
  )
  .join('\n')}

---

## 🔧 Features & Capabilities
- **System-Wide Global Hotkeys**: Works inside MS Word, Notepad, VS Code, Slack, Chrome, Edge, and any Windows software.
- **Automatic Text Selection Capture**: Automatically grabs currently highlighted text when you trigger a hotkey.
- **Floating Glassmorphic Overlay**: Displays output right next to your cursor with instant Copy, Replace, and Audio TTS.
- **Multi-Provider AI**: Google Gemini, OpenAI GPT-4o, Anthropic Claude 3.5, and local offline Ollama models.
- **100% Client-Side Privacy**: All API keys and settings stay local on your machine.

---

## ❓ Frequently Asked Questions

### Q: Why didn't my hotkey trigger in an Administrator window?
On Windows, if an app (like CMD or Task Manager) is running as Administrator, QuickKeys AI must also be launched as Administrator to capture global shortcuts over that window.

### Q: How do I run local offline AI without API keys?
Install **Ollama** on Windows ([ollama.com](https://ollama.com/)), run \`ollama run llama3.2\` in Command Prompt, and set your provider to **Ollama** in QuickKeys AI settings.
`;
}
